### PR TITLE
Create 2016-08-12-trolls-working-in-new-horizons-tgif-96.md

### PR DESCRIPTION
**Pull request by skeskali**

### CODE REVIEW

**Comment by gr2m** [comment]
This is A+, thanks so much for the great work!

Suggestion for quoting, I’d suggest this formatting:

```
> When we started the project, we had low self confidence. Even though we have taken classes on different programming languages, when it came to working with it we thought we did not have all the knowledge it took to get the job done. Now we understand that every working experience is a great opportunity to teach ourselves new things everyday.
> 
> —<cite>Tehetena and HyeSoo, [Hoodie is once again participating in the Rails Girls Summer of Code](http://hood.ie/blog/rgsoc-team-rookies-month-1.html)</cite>
```

which renders like this

> When we started the project, we had low self confidence. Even though we have taken classes on different programming languages, when it came to working with it we thought we did not have all the knowledge it took to get the job done. Now we understand that every working experience is a great opportunity to teach ourselves new things everyday.
> 
> —<cite>Tehetena and HyeSoo, [Hoodie is once again participating in the Rails Girls Summer of Code](http://hood.ie/blog/rgsoc-team-rookies-month-1.html)</cite>

**Comment by gr2m** [comment]
ohey one more thing, our friends Nadia & Mikeal just shipped their new podcast and it’s a must-listen: https://changelog.com/rfc/ can we add it to the Open Source section?

**Comment by jennwrites** [comment]
Added both suggestions @gr2m and merging now! 👍

**Comment by skeskali** [comment]
Agreed. We should also update the editorial wiki to reflect this style.

**Comment by jennwrites** [comment]
+1 I will do this right now

**Pull request merged**
