### PR TITLE
Add npm scripts to hide tools behind common interface.

### PR DESCRIPTION
**Pull request by boennemann**

### CODE REVIEW

**Comment by janl** [comment]
Just checking: does this do local gem installs only? Otherwise there might be a `sudo` issue on systems (like Mac OS X by default).

**Comment by varjmes** [comment]
This morning I was looking at the jekyll stuff and going "huh?". Thank you for this, it really helps!

However, when I run `npm run dev` I get the following:

hoodie-npm-scripts-bug

Have I done something wrong?

**Comment by boennemann** [comment]
@Charlotteis I haven't set up the underlying scripts, but as far as I understood the readme you run `npm run dev` and then `npm run serve` in another terminal. Opening localhost:4000 should give you the working site then :)

**Comment by boennemann** [comment]
@janl As far as I understood (I understood NOTHING) that's what `bundle exec` does :)

**Comment by varjmes** [comment]
@boennemann I didn't know that, thanks. Still seem to be having the same problems unfortunately :( If someone else is able to test it and it works as it should, this LGTM.

**Comment by boennemann** [comment]
Can I have a review here because I'm waiting for #169 to finish the Slack transition.
@espy @verpixelt @zoepage @janl

**Comment by janl** [comment]
```
> git clean -fdx
Removing _site/
> npm i 
npm WARN package.json hoodie-website@0.1.0 No repository field.
/
> node-sass@3.2.0 install /Users/jan/Work/hoodie/hood.ie/node_modules/grunt-sass/node_modules/node-sass
> node scripts/install.js

Binary downloaded and installed at /Users/jan/Work/hoodie/hood.ie/node_modules/grunt-sass/node_modules/node-sass/vendor/darwin-x64-11/binding.node

> node-sass@3.2.0 postinstall /Users/jan/Work/hoodie/hood.ie/node_modules/grunt-sass/node_modules/node-sass
> node scripts/build.js

` /Users/jan/Work/hoodie/hood.ie/node_modules/grunt-sass/node_modules/node-sass/vendor/darwin-x64-11/binding.node ` exists. 
 testing binary.
Binary is fine; exiting.

> hoodie-website@0.1.0 install /Users/jan/Work/hoodie/hood.ie
> bundle install

sh: /usr/bin/bundle: /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/bin/ruby: bad interpreter: No such file or directory

npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "i"
npm ERR! node v0.10.36
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE
npm ERR! hoodie-website@0.1.0 install: `bundle install`
npm ERR! Exit status 126
npm ERR! 
npm ERR! Failed at the hoodie-website@0.1.0 install script 'bundle install'.
npm ERR! This is most likely a problem with the hoodie-website package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bundle install
npm ERR! You can get their info via:
npm ERR!     npm owner ls hoodie-website
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jan/Work/hoodie/hood.ie/npm-debug.log

```

**Comment by janl** [comment]
@boennemann getting this when running the branch locally

**Comment by varjmes** [comment]
@janl I had the same problem, it was because I didn't have [bundler](http://bundler.io) installed.

**Comment by janl** [comment]
@Charlotteis ah, then the instructions need updating :)

**Comment by janl** [comment]
And a more descriptive error message would be good :)

**Comment by janl** [comment]
now getting this:

```
> npm run serve

> hoodie-website@0.1.0 serve /Users/jan/Work/hoodie/hood.ie
> npm run jekyll -- serve --watch --drafts


> hoodie-website@0.1.0 jekyll /Users/jan/Work/hoodie/hood.ie
> bundle exec jekyll serve --watch --drafts

Configuration file: /Users/jan/Work/hoodie/hood.ie/_config.yml
            Source: /Users/jan/Work/hoodie/hood.ie
       Destination: /Users/jan/Work/hoodie/hood.ie/_site
      Generating... Error reading file /Users/jan/Work/hoodie/hood.ie/_posts/2013-06-08-hoodie-presentation-at-apps-berlin-js.md: invalid byte sequence in US-ASCII
Error reading file /Users/jan/Work/hoodie/hood.ie/_posts/2013-06-08-podcast-hood-ie-on-nerds-fm.md: invalid byte sequence in US-ASCII
Error reading file /Users/jan/Work/hoodie/hood.ie/_posts/2013-06-08-talking-bout-hoodie-twitter-april-2013.md: invalid byte sequence in US-ASCII
error: invalid byte sequence in US-ASCII. Use --trace to view backtrace

npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "run" "jekyll" "--" "serve" "--watch" "--drafts"
npm ERR! node v0.10.36
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE
npm ERR! hoodie-website@0.1.0 jekyll: `bundle exec jekyll serve --watch --drafts`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hoodie-website@0.1.0 jekyll script 'bundle exec jekyll serve --watch --drafts'.
npm ERR! This is most likely a problem with the hoodie-website package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bundle exec jekyll serve --watch --drafts
npm ERR! You can get their info via:
npm ERR!     npm owner ls hoodie-website
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jan/Work/hoodie/hood.ie/npm-debug.log

npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "run" "serve"
npm ERR! node v0.10.36
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE
npm ERR! hoodie-website@0.1.0 serve: `npm run jekyll -- serve --watch --drafts`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hoodie-website@0.1.0 serve script 'npm run jekyll -- serve --watch --drafts'.
npm ERR! This is most likely a problem with the hoodie-website package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run jekyll -- serve --watch --drafts
npm ERR! You can get their info via:
npm ERR!     npm owner ls hoodie-website
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jan/Work/hoodie/hood.ie/npm-debug.log

```

The key there is: **invalid byte sequence in US-ASCII**

I didn’t have this before this patch, but I’ve seen this before and fixed it this way: https://github.com/jsconf/2014.jsconf.eu/blob/gh-pages/Makefile

Not sure why this suddenly breaks on my system, but could be that the indirect invocation of jekyll now chomps any required env vars.

**Comment by janl** [comment]
Although this is working fine for me: `LANG="en_US.UTF-8" LC_ALL="en_US.UTF-8" npm run serve`

**Comment by boennemann** [comment]
@janl The instructions were already updated with the bundler requirement: https://github.com/hoodiehq/hood.ie/commit/2abdadd862895880cd302a5a317fb1e218ca5088#diff-04c6e90faac2675aa89e2176d2eec7d8R6

Please check if this works w/o the env vars for you with the latest commit.

**Comment by janl** [comment]
yay, this works now, but I see the same thing that @Charlotteis reported:

screen shot 2015-07-08 at 12 18 52

**Comment by verpixelt** [comment]
Looks like CSS stuff isn't prefixed.

**Comment by christophwitzko** [comment]
Everything works fine for me. :+1:

**Comment by christophwitzko** [comment]
@verpixelt added this functionality in commit 25a6436. :+1:

**Comment by varjmes** [comment]
just a bit of confusion on this. by "stuff isn't prefixed" is there something I need to do to fix this? Strange. 
maybe @verpixelt can help please? :)

**Comment by zoepage** [comment]
@boennemann @christophwitzko did you fix the bug @Charlotteis mentioned before or couldn't you reproduce?

**Comment by verpixelt** [comment]
@Charlotteis

```
    autoprefixer: {
        single_file: {
            options: {
                browsers: ['last 2 versions', 'ie 11', 'ie 10', 'ie 9'],
                cascade: false,
                annotation: false
            },
            src: 'dist/prod/.tmp/hoodie.min.tmp.css',
            dest: 'dist/prod/hoodie.min.pref.css'

        }
    },
```

**Comment by varjmes** [comment]
I'm afraid I still don't understand. I'll work it out, see what I've failed to do with autoprefixer or something.

**Comment by zoepage** [comment]
We have an autoprefix task in the grunt setup that prefixes everything we need during the minify task. :)
So, the `grunt build` didn't has been run before deployment.

**Comment by verpixelt** [comment]
@Charlotteis maybe this helps to grasp the basic concept of it https://medium.com/@verpixelt/get-started-with-grunt-76d29dc25b01

**Pull request closed without merging**
