### PR TITLE
prepare TGIF 74

### PR DESCRIPTION
**Pull request by skeskali**
before merge 
- [x] rename file
- [x] set `title:` option

### CODE REVIEW

**Comment by janl** [comment]
@skeskali I’ve removed the swearing video because it starts with dangerous traffic situations and I know those can be triggering to people (I couldn’t watch more than 5 or so seconds).

To make up for it, I added a few things :)

**Comment by gr2m** [comment]
I will add the shout outs and updates etc later today

**Comment by gr2m** [comment]
Let’s add a link to Jenn’s Blog Post:
http://hood.ie/blog/shaping-an-open-source-editorial-team.html

**Comment by gr2m** [comment]
I’ve mentioned @renrutnnej’s blog post in the "Contribute to Hoodie" Section: https://github.com/hoodiehq/hood.ie/commit/d82569261433bff72cca660d7ff5f67646d187d6

**Comment by gr2m** [comment]
please if you could have a look at the shout outs, I want to make sure I didn’t accidentally forgot someone https://github.com/hoodiehq/hood.ie/commit/25e8615be645c74080a83279201c60c011d3f0ee ([Preview](https://github.com/hoodiehq/hood.ie/blob/25e8615be645c74080a83279201c60c011d3f0ee/_posts/2016-03-11-tbd.md#shout-outs--mega))

**Comment by gr2m** [comment]
OMG let’s add this: https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments

**Comment by skeskali** [comment]
I'm happy with all of the changes (and continued support).

**Comment by jennwrites** [comment]
Just noticed the last header isn't rendering for some reason. Otherwise +1 from me. Thanks for all the work @skeskali and @gr2m and @janl :sparkling_heart:

**Comment by janl** [comment]
I‘m working on fixing the markup.

**Comment by janl** [comment]
For next time, things that don’t work on our blog, but look fine within GitHub: 
- `:emojiname:`, use literal emoji. e.g. 📣 instead of `:mega:`
- backticks for “code”. Use `*` or `**` to wrap. (this can be fixed in our CSS, but currently isn’t.)
- standalone URLs are not rendered into links. always use `[link label](url)`

**Comment by lewiscowper** [comment]
Is the blog bear bio link supposed to go to edit mode directly? That seems moderately unsafe...

**Comment by janl** [comment]
ah yikes. thanks!

**Comment by janl** [comment]
taking that out until we have something to show properly.

**Comment by HipsterBrown** [comment]
LGTM :+1:

**Comment by lewiscowper** [comment]
LGTM :+1:

**Comment by jennwrites** [comment]
+1

**Comment by janl** [comment]
here we gooooo

**Comment by janl** [comment]
And we’re live, thanks everybody: http://hood.ie/blog/lave-revision-artificial-maker.html :)

**Comment by gr2m** [comment]
forgot the `-tgif-74` suffix, but I wouldn’t change it anymore :)

**Pull request merged**
