### PR TITLE
draft post of FLOSS interview synopsis

### PR DESCRIPTION
**Pull request by sjnorth**
Preview: https://github.com/hoodiehq/hood.ie/blob/sjnorth-patch-1/_posts/2016-03-16-choose-your-own-adventure.md

### CODE REVIEW

**Comment by janl** [comment]
lgtm!

**Comment by gr2m** [comment]
This is very nice! 

Two suggestions
1. replace `co-founder` with something like `co-initiator`? `co-founder` sounds like Hoodie would be a business to me which it’s not, I’d like to avoid that perception if possible. Does that make sense?
2. shall we add a screenshot of the 4 pretty faces that links to the show?

**Comment by jennwrites** [comment]
Good suggestions @gr2m! I'll do both now.

**Comment by jennwrites** [comment]
LGTM

**Comment by janl** [comment]
LGTM

hope this helps

**Comment by HipsterBrown** [comment]
Awesome work @sjnorth! :+1:

**Pull request merged**
