### PR TITLE
Remove cursor: pointer from the header

### PR DESCRIPTION
**Pull request by NickColley**
Hello!

The new website is looking super smart, great work. :dancer: 

I noticed the header has cursor: pointer on it which makes the entire navigation highlight when interacting with it on Chrome for Android.

screenshot_2014-11-11-19-30-12

### CODE REVIEW

**Comment by verpixelt** [comment]
Hey Nick,
thanks for your feedback and the pull request. I assume that removing `cursor: pointer` solves just a part of the problem. In our main.js we define the whole `<header>` as click area to open the navigation. I'll check on that tomorrow when I have a Android device near me. Which Android version are you running?

**Comment by NickColley** [comment]
Cheers for replying so quickly :)

Some info:

Model number:
Nexus 4
Android version:
4.4.4
Chrome version:
38.0.2125.114

**Comment by verpixelt** [comment]
Hey @nickcolley we've changed a few things regarding the navigation. Is this (beside the cursor: pointer thing) still an issue for you?

**Comment by NickColley** [comment]
Is the intended behaviour for the menu to extend no matter where you click it? At the moment it only works when you press the icon itself.

Having cursor pointer across the entire nav makes it difficult to know what's a link and what's not.

It's better now though for sure though, thanks for your time.

**Comment by verpixelt** [comment]
As I mentioned, at this point the whole `<header>` is the clicking area. We'll change that in the JS files so that you have to hit the menu button. Thanks for your time and your help pointing out that problem.

**Pull request closed without merging**
