### PR TITLE
Add an alumni section

### PR DESCRIPTION
**Pull request by sxosxo**
Fixes https://github.com/hoodiehq/editorial/issues/68

Creation of alumni section. Then moving seven persons from the COMMUNITY section into the new ALUMNI section.

### CODE REVIEW

**Comment by gr2m** [comment]
thanks Sonja, LGTM :) I’ll wait for a 2nd review and then we merge it in 👌

**Comment by jennwrites** [comment]
LGTM

**Comment by sxosxo** [comment]
Sweet 😊

**Comment by HipsterBrown** [comment]
LGTM 🚀 👍

**Comment by jennwrites** [comment]
Does this resolve https://github.com/hoodiehq/editorial/issues/68 also?

**Comment by gr2m** [comment]
> Does this resolve hoodiehq/editorial#68 also?

I’d say yes. If you agree, let’s close it :)

**Comment by jennwrites** [comment]
I amended the issue description above for when this gets merged 👍

**Comment by gr2m** [comment]
merged via 59a3389

**Comment by gr2m** [comment]
Thanks a lot @SonjaHeinen! I’m so sorry it took us so long to get your work merged, I promise it usually doesn’t take this long at all. If you’d like to look into something else, we prepared issues here: https://github.com/hoodiehq/camp/issues if you have any further questions or would like to make a call to just chat, I’d be happy to :)

**Pull request closed without merging**
