### PR TITLE
Introducing Development Beaver

### PR DESCRIPTION
**Pull request by jennwrites**
Fixes https://github.com/hoodiehq/editorial/issues/65

Created by the very talented @annaboodle _ages_ ago, and very deserving of getting out into the world of Hoodie and beyond!

Please review and comment!

### CODE REVIEW

**Comment by gr2m** [comment]
I think we discussed to name the dev beaver Charlie and use `they/them` for pronouns. 

Regarding the names, we want to find names for all animals including the existing ones, so we can make up stories in our code tests, where we often times would need a `name` property for testing

**Comment by jennwrites** [comment]
That's correct, Charlie is the name. I just wasn't sure where to publish that information because I don't know that any of the other animals have names beyond their descriptor names. 

Also +1 on they/them

**Comment by gr2m** [comment]
> That's correct, Charlie is the name. I just wasn't sure where to publish that information because I don't know that any of the other animals have names beyond their descriptor names. 

ah that makes sense! Yeah don’t worry then, we can add the names later :)

**Comment by machikoyasuda** [comment]
Riveting. I love this story!!!!!!!

**Comment by janl** [comment]
lgtm!

**Comment by jennwrites** [comment]
I updated the pronouns per discussion with @gr2m so if everyone else approved of the story beyond that point, I'm going to move forward with publishing now!

**Pull request merged**
