### PR TITLE
RGSoC Team Rookies 2nd blog 

### PR DESCRIPTION
**Pull request by flyjwayur**
Hey,
We are HyeSoo and Tehetena from RGSOC team Rookies :) 
We would like to share our #2 part of our summer journey with Hoodie. 
Thank you so much for all the helps and supports. 
It has been really happy August for both of us. 
If there is anything we need to edit, please feel free to let us know. 
We are happy to listen opinions/advice. 
Have a wonderful day :D 

(The issue #325 is related with this pull request)

### CODE REVIEW

**Comment by gr2m** [comment]
Shall we add a link to the first post in there?

**Comment by jennwrites** [comment]
This is great work Team Rookies! I'm so happy to read about your RGSoC experience ☺️ 

I did a full edit so please review @flyjwayur and @titay2 (and @gr2m) and we can move forward with publishing. 💃

**Comment by janl** [comment]
lgtm

**Comment by jennwrites** [comment]
LGTM!

**Comment by flyjwayur** [comment]
@gr2m @renrutnnej @janl Gregor, Jenn, Jan, thank you so much for the kind feedback and helping us to improve our blog post. We love the edited our blog post :)

**Pull request merged**
