### PR TITLE
This week's TGIF post

### PR DESCRIPTION
**Pull request by jennwrites**
Please review!

### CODE REVIEW

**Comment by HipsterBrown** [comment]
Fantastic links once again! LGTM :+1:

**Comment by finnp** [comment]
Great collection of links :relaxed:

**Comment by finnp** [comment]
@renrutnnej I just noticed that NodeSchool is March 22nd not March 21st though.

**Comment by jennwrites** [comment]
Ooh thanks for picking up on that!

-- 
Jenn Turner
I ❤️ great email at jennwrit.es/newsletters 

On March 18, 2016 at 12:14:28 PM, Finn Pauls (notifications@github.com) wrote:

@renrutnnej I just noticed that NodeSchool is March 22nd not March 21st though.

**Comment by janl** [comment]
I’m adding few pull-quotes now.

**Comment by janl** [comment]
would love a once-over for my changes <3 — Happy to publish this right after :)

**Comment by gr2m** [comment]
LGTM thanks for jumping in @renrutnnej <3

**Pull request merged**
