### PR TITLE
[RFR] fix(a11y): add alt text to header logo

### PR DESCRIPTION
**Pull request by KittyGiraudel**
Fixes https://github.com/hoodiehq/hood.ie/issues/223. Also took the opportunity to create a partial to avoid such tedious changes in the future.

Cheers.

### CODE REVIEW

**Comment by NickColley** [comment]
:+1: for the use of a partial

**Comment by KittyGiraudel** [comment]
On topic, you have a lot of duplicated code across the various header partials. I am pretty sure it would be easy to factorize.

**Comment by varjmes** [comment]
Hey @HugoGiraudel, thanks for this!

You are quite right in there is a lot of duplicate across the headers. Feel free to work on a fix if you think you're able, else I will be happy to write that up into it's own issue!

This is a great fix and I'll try and get this merged soon. :sparkles:

**Comment by KittyGiraudel** [comment]
If I can find some time this week, I’ll try to optimise your Liquid partials. :)

**Comment by gr2m** [comment]
:clap: thanks @HugoGiraudel, @Charlotteis & @nickcolley

**Pull request merged**
