### PR TITLE
Update Footer links and language

### PR DESCRIPTION
**Pull request by kazekagegaara**
Changes as mentioned in #231

### CODE REVIEW

**Comment by varjmes** [comment]
LGTM :+1:

**Comment by kazekagegaara** [comment]
@Charlotteis should I close the pull request? Or someone from your team will do that?

**Comment by varjmes** [comment]
@kazekagegaara I'd like to see if @renrutnnej is happy with it as they wrote the original issue and then they can press the merge button! thanks for contributing!!

**Comment by kazekagegaara** [comment]
ok. Thank you for letting me contribute!

**Comment by jennwrites** [comment]
LGTM :+1:

**Comment by NickColley** [comment]
Thanks @kazekagegaara :D

**Pull request merged**
