### PR TITLE
Fixed typos, etc.

### PR DESCRIPTION
**Pull request by ayushi-jha**
Hi, I was reading through the article, and this pull request is related to small typos, grammatical errors etc. that I came across. Wonderful article, by the way.

### CODE REVIEW

**Comment by jennwrites** [comment]
LGTM

Thanks @ayushi-jha for the edits! Can I get @gr2m to sign off on this too?

**Comment by machikoyasuda** [comment]
Thank you @ayushi-jha for your edits!!

**Comment by gr2m** [comment]
This is great, thanks so much @ayushi-jha 👏 LGTM

**Comment by ayushi-jha** [comment]
Thanks all! This is my first merged pull request!

**Comment by gr2m** [comment]
zomg welcome 👏 🎉 🐶 this is very exciting, we are honored to be the project you choose to send a pull request to first :) And welcome at Hoodie! Oh and are you on twitter by chance? We like to give shout outs to new contributors, only if you like of course

**Comment by ayushi-jha** [comment]
Thank you 😄 👍 Yes, I am on twitter @ayushi_jha_. Just followed hoodiehq there.

**Pull request merged**
