### PR TITLE
Create 2016-06-10-TGIF-87.tbd

### PR DESCRIPTION
**Pull request by skeskali**

### CODE REVIEW

**Comment by jennwrites** [comment]
LGTM!

**Comment by janl** [comment]
LGTM, great work! <3

Checked format locally, looks all good.

One little nitpick (doesn’t have to be fixed right away, can be just remembered for next time):

```
<cite> Some quote about stuff</cite>
[That author](http://link-to-thing.com)
```

will create a quote + attribution like so:

screen shot 2016-06-10 at 18 25 59

Whereas we do this here:

```
<cite> Some quote about stuff</cite>

[That author](http://link-to-thing.com)
```

(extra newline)

And it creates this type of quote and a link:

screen shot 2016-06-10 at 18 27 01

I don’t think this is a big deal by any stretch, but I think the former is nicer and conforms to how we planned the citation/attribution design for the blog ;)

Again, no need to fix this now (unless you feel like it), just remember for next time!

**Comment by nathanstilwell** [comment]
I got thrown by the blockquotes a little too. But everything else looks great.

👍 👍 :shipit:

**Comment by skeskali** [comment]
I'll fix it when I get to the office in about an hour. 😊

**Comment by gr2m** [comment]
LGTM

**Pull request merged**
