### PR TITLE
TGIF 99

### PR DESCRIPTION
**Pull request by machikoyasuda**
Hi friends - Here's my TGIF LA edition draft!

### CODE REVIEW

**Comment by machikoyasuda** [comment]
I will be driving around LA today... delivering stickers among other things.. so I won't be around at my computer to do anything for the rest of the day! 🚗 ☀️ Maybe this newsletter needs more emojis or photos? Not sure.

**Comment by gr2m** [comment]
It’s a different style of TGIFs compared to previous ones but I like it :) LGTM

Just a question regarding the "Software Craftsmanship" event: will you speak or attend?

**Comment by gr2m** [comment]
For events, aren’t you @renrutnnej  at a conference in Amsterdam sometime soon?

**Comment by janl** [comment]
LGTM

**Pull request merged**
