### PR TITLE
introducing fixes for consistency and content

### LINKED ISSUE #215: Code of Conduct inconsistencies
# The Issue

From: http://hood.ie/code-of-conduct/

> Thus, we are committed to providing a friendly, safe and welcoming environment for everyone, regardless of gender, sexual orientation, personal ability or disability, ethnicity, religion, level of experience, set of skills or similar personal characteristic.

---

> In alphabetical order, some of these attributes include (but are not limited to): age, culture, ethnicity, gender identity or expression, national origin, physical or mental difference, politics, race, religion, sex, sexual orientation, socio-economic status, and subculture. We welcome people regardless of the values of these or other attributes.

---

> Harassment includes offensive verbal comments related to gender, sexual orientation, disability, physical appearance, body size, race, religion, sexual images in public spaces, deliberate intimidation, stalking, following, harassing photography or recording, inappropriate physical contact, and unwelcome sexual attention.

Three paragraphs about what we won't allow, but none of them are the same. The top one is the first thing you see and it is not as detailed as other ones. I wanted to add "gender identity and expression" and was sad that we didn't mention it, then saw we **did** say it if I scrolled a lot further down, and then if I scrolled even further down it was not mentioned again in the last paragraph I pasted. 
# The Solution

Could we have some consistency in these paragraphs? Make the "things we do discriminate against" pargaphs can we have the same full list each time? One for the Editorial team perhaps.
# Steps to Solve
- Fork this repository
- Make a new git branch
- Make your edits in `code-of-conduct/index.html` file
- Commit and push to your repository
- Make a Pull Request

**OR**
- Make the edits directly in the browser on this file: https://github.com/hoodiehq/hood.ie/blob/gh-pages/code-of-conduct/index.html and GitHub will guide you through how to commit and pull request your changes.

:sparkling_heart: :sparkles: :pencil2: :notebook:

### PR DESCRIPTION
**Pull request by lenareinhard**
- fix 3 broken links that were Google Referral links
- optimise “dont’s” for consistency, fix #215
- include use of profanity
- capitalise “Code of Conduct”
- mention Slack
- remove Lena as contact person

### CODE REVIEW

**Comment by NickColley** [comment]
This looks really good! :+1:

**Comment by lenareinhard** [comment]
@mikehedman thanks a lot for the feedback, Mike! That's super helpful.

**Comment by gr2m** [comment]
this is great, thanks @ffffux :+1:

**Comment by lenareinhard** [comment]
Thanks, @gr2m! 
Added all proposed fixes. (Also, now I know how to update a Pull Request (I think) 🐳🚀✨)

**Comment by varjmes** [comment]
Amazing, thank you so much @ffffux :)

**Comment by janl** [comment]
shippetyship

**Pull request merged**
