### PR TITLE
TGIF 73: Shout Outs, Hoodie Camp Release, GOAT!

### PR DESCRIPTION
**Pull request by gr2m**

### CODE REVIEW

**Comment by skeskali** [comment]
Thanks so much for the help everyone!

**Comment by gr2m** [comment]
Forgot: wanted to mention everyone who contributed this week to Hoodie: @Charlotteis, @crswll, @jsimplicio, @nathanstilwell, @nickcolley, @skeskali, @stehuebn, @stevemasta34 – we gave you a shout out at our latest TGIF :) http://hood.ie/blog/terrier-open-source-sensitive-democracy-for-hamilton-tiles-tgif-73.html (Shout outs 📣)

Thanks for your help :+1:

**Comment by jsimplicio** [comment]
:+1: Awesome work!

**Comment by stehuebn** [comment]
Thank You! :-)

**Pull request merged**
