### PR TITLE
Better font loading

### PR DESCRIPTION
**Pull request by verpixelt**

### CODE REVIEW

**Comment by NickColley** [comment]
@verpixelt have you looked into http://www.filamentgroup.com/lab/font-events.html ?
I've had good success with that approach. Can help out if you're interested.

**Comment by verpixelt** [comment]
Hey Nick, thanks for the offer. I've already implemented a solution which works pretty good ;) There's just an issue with the font subsetting and the ligatures. But I'm working on that #134 ;)

**Comment by NickColley** [comment]
Sweet, thought I'd give it a mention because that approach doesn't require base64 encoding.

**Comment by verpixelt** [comment]
Yeah thanks =) I had the article already stored in my Pocket account. At the moment I'm pretty happy with the idea to store the base64 encoded font files inside localStorage. But Fira Sans and the base64 encoding are giving me a big headache right now. Either it is Font Squirrel which causes the pain or the different versions of Fira Sans out there. I'm not sure at the given moment.

**Pull request merged**
