### PR TITLE
TGIF 69

### PR DESCRIPTION
**Pull request by juschm**
Thought I would find some more things on the morning news round, but there wasn't much, so maybe you have some more open source and fun stuff up your sleeve?! Anyway - hopefully you had an above average week, will have not too much stress today and a nice weekend! <3 (communication will be better in two weeks time - promise!)

### CODE REVIEW

**Comment by juschm** [comment]
I added some things, seeing that this hasn't been used yet. If something's wrong, please don't hesitate to get in touch. :)

**Comment by janl** [comment]
Heya @juschm: I ended up running out of time today, so I’ll post this first thing in the morning :) Thanks again!

**Comment by janl** [comment]
So, finally! <3

**Comment by janl** [comment]
Das war wieder eine super Ausgabe!

**Pull request merged**
