### PR TITLE
feat(blog): added meet charlotte post 

### PR DESCRIPTION
**Pull request by espy**
…with optimized images in dist1 and espy as additional contributor :)

### CODE REVIEW

**Comment by schisepo** [comment]
Thanks @espy. Looks good to me.

**Comment by varjmes** [comment]
LGTM! Thank you!

**Comment by janl** [comment]
If nobody objects, (or beats me to it), I’ll merge this just before 10am CET and announce this on twitter.

Thanks everybody! <3

**Comment by varjmes** [comment]
yayayayayayayyayayaya

**Comment by janl** [comment]
boom boom boom boom

**Pull request merged**
