### PR TITLE
blog post: Deploy Hoodie apps with one line

### PR DESCRIPTION
**Pull request by gr2m**
[Preview](https://github.com/hoodiehq/hood.ie/blob/9bc6e96b67564f7d8c2d66f51170ac5a6ffd9763/_posts/2017-01-31_single-line-deployment.md) 🎉 

Video is here: ~~https://youtu.be/OVWCnEmjZBc~~ https://youtu.be/29Uclxq_1Vw

### CODE REVIEW

**Comment by janl** [comment]
Great post, but the formatting doesn’t work. We still have this thing where the css doesn’t do inline `code` properly:

screen shot 2017-01-31 at 12 56 12

**Comment by janl** [comment]
I really like the video too, it shows something we’ve wanted for a couple of years now and I’m glad we finally got there :)

A few comments:
- at 1:15: you say you need to install `now` with `now install -g now`, you mean npm, you also type this in the console, we should get that fixed.
- when you specify the GitHub repo, you say “slug”, not everybody might know what that is, I’d suggest saying “repository name” or “repository location”
- When you do sign-in stuff, a flurry of 1password things happen and it is VERY confusing. Maybe we can do the demo on a pristine browser, so nothing distracts?
- I’d also recommend using a separate demo account on Cloudant, and not sharing it’s password in a video. Best way I can think of right now to do this is running `export CLOUDANT_PASSWORD=thepassword` in the terminal before the screencast starts and then specifying it like this: `…-e hoodie_dbUrl=https://admin:$CLOUDANT_PASSWORD@hoodie-demo.cloudant.com`.
- Also, we should use `https` there, so the now <> Cloudant communication is secured). I think Cloudant upgrades you automatically anyway, but this way people are never in doubt. #httpseverywhere
- It might be a good idea to transcribe the current video into notes that you read for a new recording. There are quite a few “uhms” and pauses in there. I’d also hope we can cut the demo video in half, just so more people will watch it :) — I’m happy to help with editing the script, I remember a few odds and ends that we could cut from a first-run video like this.

Anyway, I LOOOOOOVE this, and I just want to make sure we make this really good. Happy to help with any part of this.

**Comment by jennwrites** [comment]
I reviewed and added some small fixes. Happy to see the blog getting some love ❤️🎉

**Comment by gr2m** [comment]
I’ve fixed the styling of inline CSS and updated the video:
https://youtu.be/29Uclxq_1Vw

I know it’s not perfect but only have so much time :( If anyone wants to edit it, here is the source video before editing: https://dl.dropboxusercontent.com/u/732913/tmp/screencast2.mov

I’d like to publish it as @terichadbourne is working on a blog post about a related topic and would like to link to this one :)

**Comment by janl** [comment]
@gr2m niiiiiiiiice work <3333 :ship:

**Comment by janl** [comment]
well, inline styles still bork, can you please run `jekyll serve` locally to test this?

screen shot 2017-02-01 at 22 03 35

**Pull request merged**
