### PR TITLE
/contribute page updates

### PR DESCRIPTION
**Pull request by gr2m**
part of https://github.com/hoodiehq/hood.ie/issues/234
- [x] Insert actionable section
- [x] Remove the `Hire us!` section/icon
- [x] Remove the `Merchandise` section/icon
- [x] update [Write Content](http://hood.ie/contribute/#writing) section

### CODE REVIEW

**Comment by gr2m** [comment]
okay this is ready for review. Here is a PDF of the new version for simple review:
[hoodie-contribute-page.pdf](https://github.com/hoodiehq/hood.ie/files/151620/hoodie-contribute-page.pdf)

**Comment by jennwrites** [comment]
I noticed a typo in one of the headers that should read “Start a meetup…” otherwise I think it looks good +1

-- 
Jenn Turner
😎Human being at jennpm.com😎

On February 29, 2016 at 2:40:32 PM, Gregor Martynus (notifications@github.com) wrote:

okay this is ready for review. Here is a PDF of the new version for simple review:
hoodie-contribute-page.pdf

**Comment by gr2m** [comment]
:+1:  Fixed the typo in `Start a meetup`

**Comment by janl** [comment]
lgtm

**Pull request merged**
