### PR TITLE
remove white text shadow around links and change aside to higher contrast gray

### PR DESCRIPTION
**Pull request by HipsterBrown**
The link text was hard to read with the white text-shadow style on them, so I removed it to increase legibility. I also increased the contrast of the gray aside text from $gray-4 to $gray-2 to make it more readable as well. 

PR reference screenshot

### CODE REVIEW

**Comment by HipsterBrown** [comment]
Screenshot of the visual change. 

PR change screenshot

**Comment by verpixelt** [comment]
Hey Nick,
thanks for your feedback. We appreciate that a lot. The white text-shadow is actually there for interrupting the link underline when descenders cross it. We've adjusted the text-shadow colour if links are placed on a coloured background. I can't see any problem with doing so. Can you explain where this orange background-colour of yours comes from?

**Comment by HipsterBrown** [comment]
Ah ok, that makes sense. The orange background is on the intro.html page. That's where I took the screenshot. Thanks for clarifying that.

**Comment by verpixelt** [comment]
That's interesting. This is how I see the page and how it should look like:
text-shadow
Which OS/browser combination do you use?

**Comment by HipsterBrown** [comment]
I was using the latest Chrome on my work iMac running Yosemite. My Macbook Pro doesn't show the orange background on Chrome or Safari. How interesting. If I can recreate it at work again, I'll try another PR with a fix. 

That basically makes this PR useless until then. Thanks for your help.

**Comment by HipsterBrown** [comment]
I am still in favor of increasing the contrast of the gray aside text because it's too low on the light/white backgrounds.

**Comment by HipsterBrown** [comment]
Discovered the issue showing the orange background on items with the orange class. One of my Chrome extensions, Hootsuite Hootlet, that was adding that class style for some reason.

**Comment by verpixelt** [comment]
Hey @HipsterBrown I can understand your concerns regarding readability and we want to thank you for pointing out. Nevertheless we wont merge it. Everything inside the sidebar is just meant to be additional information. You still understand the whole main content without reading them. Therefor we decided on purpose to set this side notes in a much lighter grey so we won't disturb the reading flow too much. I hope this makes it comprehensible.

**Comment by HipsterBrown** [comment]
Thanks for the explanation @verpixelt. I can follow along with that design decision and appreciate the thought you all put into it. It makes much more sense without the orange background. ;)

**Pull request closed without merging**
